spring.application.name=backend
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/Entrenamiento}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:_____}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.debug=true
logging.level.root=INFO
logging.level.com.sharentrenamiento.app=DEBUG
